import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'http://localhost:4000/api';
const statusColumns = [{ id: 'todo', label: 'To do', tone: 'gray' }, { id: 'progress', label: 'In progress', tone: 'blue' }, { id: 'done', label: 'Completed', tone: 'green' }];
const icons = { search: '⌕', bell: '♢', plus: '+', grid: '▦', list: '☷', calendar: '□', more: '•••', comment: '◌', filter: '≡' };

function Avatar({ user, small = false }) { return <span className={`avatar ${small ? 'small' : ''}`} style={{ background: user?.color }}>{user?.initials || '??'}</span>; }
function Login({ onLogin }) {
  const [email, setEmail] = useState('alex@flowboard.dev'); const [password, setPassword] = useState('demo123'); const [error, setError] = useState('');
  const submit = (e) => { e.preventDefault(); fetch(`${API}/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }).then(async (r) => { const result = await r.json(); if (!r.ok) throw new Error(result.error); localStorage.setItem('flowboard-token', result.token); onLogin(); }).catch((err) => setError(err.message)); };
  return <div className="auth-shell"><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark">✦</span> flowboard</div><h1>Welcome back</h1><p>Sign in to continue to your workspace.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <div className="auth-error">{error}</div>}<button className="primary auth-submit">Sign in</button></form><small>Demo password: <b>demo123</b></small></div></div>;
}
function App() {
  const [authenticated, setAuthenticated] = useState(Boolean(localStorage.getItem('flowboard-token')));
  const [data, setData] = useState(null); const [activeProject, setActiveProject] = useState('p1'); const [selected, setSelected] = useState(null);
  const [view, setView] = useState('board'); const [query, setQuery] = useState(''); const [showNew, setShowNew] = useState(false); const [showNotif, setShowNotif] = useState(false);
  useEffect(() => { if (!authenticated) return undefined; fetch(`${API}/bootstrap`).then((r) => r.json()).then(setData); const events = new EventSource(`${API}/events`); events.onmessage = (e) => { const event = JSON.parse(e.data); if (event.type === 'task.updated') setData((d) => ({ ...d, tasks: d.tasks.map((t) => t.id === event.task.id ? event.task : t) })); if (event.type === 'task.created') setData((d) => ({ ...d, tasks: [...d.tasks, event.task] })); }; return () => events.close(); }, [authenticated]);
  if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />;
  if (!data) return <div className="loading">Loading your workspace...</div>;
  const project = data.projects.find((p) => p.id === activeProject); const members = data.users.filter((u) => project.members.includes(u.id));
  const projectTasks = data.tasks.filter((t) => t.projectId === activeProject && t.title.toLowerCase().includes(query.toLowerCase()));
  const updateTask = (id, patch) => fetch(`${API}/tasks/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) });
  return <div className="app">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span> flowboard</div><div className="workspace"><Avatar user={data.user} /><div><strong>Acme Studio</strong><span>Workspace</span></div><span className="chevron">⌄</span></div>
      <nav><a className="nav-active"><span>▦</span> My work <b>4</b></a><a><span>♧</span> Inbox <b className="inbox">2</b></a><a><span>□</span> Calendar</a></nav><div className="section-title">Projects <button onClick={() => setShowNew(true)}>+</button></div>
      <div className="project-list">{data.projects.map((p) => <button className={p.id === activeProject ? 'project active' : 'project'} onClick={() => setActiveProject(p.id)} key={p.id}><i style={{ background: p.color }} />{p.name}<span>•••</span></button>)}</div>
      <div className="sidebar-bottom"><a>⚙ Settings</a><a>？ Help & resources</a><div className="upgrade"><strong>Unlock your team's potential</strong><span>Try Pro free for 14 days.</span><button>Try Pro free <b>→</b></button></div></div>
    </aside>
    <main><header><div className="breadcrumbs">Projects <span>/</span> <strong>{project.name}</strong></div><div className="header-actions"><label className="search">{icons.search}<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search" /></label><button className="icon-btn" onClick={() => setShowNotif(!showNotif)}>{icons.bell}<em>3</em></button><Avatar user={data.user} /><button className="user-menu">Alex Morgan⌄</button></div>{showNotif && <div className="notifications"><strong>Notifications</strong><p><b>Maya</b> commented on homepage copy</p><p><b>Jordan</b> completed a wireframe</p><p><b>Sam</b> mentioned you in QA</p></div>}</header>
      <div className="content"><div className="project-heading"><div><div className="title-row"><h1>{project.name}</h1><button className="star">☆</button></div><p>{project.description}</p></div><div className="heading-actions"><div className="member-stack">{members.map((m) => <Avatar key={m.id} user={m} small />)}<button>+</button></div><button className="share">Share</button><button className="primary" onClick={() => setShowNew(true)}>+ Add task</button></div></div>
        <div className="toolbar"><div className="tabs"><button className={view === 'board' ? 'tab active' : 'tab'} onClick={() => setView('board')}>▦ Board</button><button className={view === 'list' ? 'tab active' : 'tab'} onClick={() => setView('list')}>☷ List</button><button className="tab" onClick={() => setView('calendar')}>□ Calendar</button></div><div className="toolbar-right"><button>≡ Filter</button><button>↕ Sort</button><button className="more">•••</button></div></div>
        {view === 'board' ? <div className="board">{statusColumns.map((col) => <section className="column" key={col.id}><div className="column-title"><span className={`dot ${col.tone}`} />{col.label}<span className="count">{projectTasks.filter((t) => t.status === col.id).length}</span><button>+</button></div>{projectTasks.filter((t) => t.status === col.id).map((task) => <TaskCard key={task.id} task={task} users={data.users} onOpen={() => setSelected(task)} onDrop={(status) => { updateTask(task.id, { status }); setData((d) => ({ ...d, tasks: d.tasks.map((t) => t.id === task.id ? { ...t, status } : t) })); }} />)}<button className="add-card" onClick={() => setShowNew(true)}>+ Add task</button></section>)}</div> : <TaskList tasks={projectTasks} users={data.users} onOpen={setSelected} />}
      </div>
    </main>
    {selected && <TaskModal task={selected} users={data.users} onClose={() => setSelected(null)} onUpdate={(patch) => { updateTask(selected.id, patch); setSelected({ ...selected, ...patch }); setData((d) => ({ ...d, tasks: d.tasks.map((t) => t.id === selected.id ? { ...t, ...patch } : t) })); }} />}
    {showNew && <NewTask projectId={activeProject} users={data.users} onClose={() => setShowNew(false)} onCreate={(task) => { fetch(`${API}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(task) }); setShowNew(false); }} />}
  </div>;
}
function TaskCard({ task, users, onOpen, onDrop }) { const assignee = users.find((u) => u.id === task.assignee); return <article className="task-card" draggable onDragEnd={(e) => e.dataTransfer.dropEffect = 'move'} onDragStart={(e) => e.dataTransfer.setData('task', task.id)} onClick={onOpen}><div className="task-top"><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><button onClick={(e) => e.stopPropagation()}>•••</button></div><h3>{task.title}</h3><p>{task.description}</p><div className="tags">{task.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="task-meta"><span className="due">◷ {task.due}</span><span>◌ {task.comments}</span><Avatar user={assignee} small /></div></article>; }
function TaskList({ tasks, users, onOpen }) { return <div className="list-view">{tasks.map((task) => <button className="list-row" key={task.id} onClick={() => onOpen(task)}><span className={`dot ${task.status === 'done' ? 'green' : task.status === 'progress' ? 'blue' : 'gray'}`} /><strong>{task.title}</strong><span>{task.priority}</span><span>{task.due}</span><Avatar user={users.find((u) => u.id === task.assignee)} small /></button>)}</div>; }
function TaskModal({ task, users, onClose, onUpdate }) { const [text, setText] = useState(''); const [comments, setComments] = useState([]); useEffect(() => { fetch(`${API}/tasks/${task.id}/comments`).then((r) => r.json()).then(setComments); }, [task.id]); const submit = () => { if (!text.trim()) return; fetch(`${API}/tasks/${task.id}/comments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }).then((r) => r.json()).then((c) => { setComments([...comments, c]); setText(''); }); }; return <div className="overlay" onClick={onClose}><div className="modal" onClick={(e) => e.stopPropagation()}><button className="close" onClick={onClose}>×</button><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority} priority</span><h2>{task.title}</h2><p className="modal-description">{task.description}</p><div className="modal-fields"><label>Status<select value={task.status} onChange={(e) => onUpdate({ status: e.target.value })}>{statusColumns.map((c) => <option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label>Assignee<select value={task.assignee} onChange={(e) => onUpdate({ assignee: e.target.value })}>{users.map((u) => <option value={u.id} key={u.id}>{u.name}</option>)}</select></label></div><h4>Comments <span>{comments.length}</span></h4><div className="comments">{comments.map((c) => <div className="comment" key={c.id}><Avatar user={users.find((u) => u.id === c.userId)} small /><div><strong>{users.find((u) => u.id === c.userId)?.name}</strong><small>{c.time}</small><p>{c.text}</p></div></div>)}</div><div className="comment-box"><Avatar user={users[0]} small /><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && submit()} placeholder="Write a comment..." /><button onClick={submit}>Send</button></div></div></div>; }
function NewTask({ projectId, users, onClose, onCreate }) { const [title, setTitle] = useState(''); return <div className="overlay" onClick={onClose}><div className="modal new-task" onClick={(e) => e.stopPropagation()}><button className="close" onClick={onClose}>×</button><h2>Create a task</h2><label>Task name<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Review launch checklist" /></label><label>Description<textarea placeholder="What needs to be done?" /></label><div className="modal-fields"><label>Assignee<select defaultValue="u1">{users.map((u) => <option value={u.id} key={u.id}>{u.name}</option>)}</select></label><label>Priority<select defaultValue="Medium"><option>Low</option><option>Medium</option><option>High</option></select></label></div><button className="primary create" disabled={!title.trim()} onClick={() => onCreate({ projectId, title, description: 'A new task to keep the team moving.', status: 'todo', priority: 'Medium', assignee: 'u1', due: 'No due date' })}>Create task</button></div></div>; }
createRoot(document.getElementById('root')).render(<App />);
